# Generated by Django 3.2 on 2021-06-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tastingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tastingprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tastingprofile'),
        ),
    ]
